import Head from 'next/head'
import { Article } from '../src/Blog/Article/Article'
import { Header } from '../src/Blog/Header/Header'
import { Main } from '../src/Blog/Main/Main'
import { Profile } from '../src/Blog/Profile/Profile'

import { Footer } from '../src/components/Footer/Footer'

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>BLOG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Article />
      <div className={styles.contents}>
        <Main />
        <Profile />

      </div>
      <Footer />
    </div>
  )
}
