import Head from 'next/head'
import { Header } from '../src/Menu/Header/Header'
import { Work } from '../src/Menu/Work/Work'
import styles from '../styles/Home.module.css'



export default function Home() {
  return (
    <div className={styles.contact}>
      <Head>
        <title>Menu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Work />
      {/* <Designer /> */}
      {/* <Programmer /> */}
    </div>
  )
}
